@echo off
REM /*** GITHUB CONFIG VARIABLES ***/
SET GIT_USER_NAME=testRepo
SET GIT_EMAIL=gustavo.avila@softexpert.com
SET GITHUB_ORGANIZATION=GustavoAvilaSE
SET GITHUB_REPOSITORY_NAME=testRepo

REM /*** LOCAL SOURCES CONFIG VARIABLE ***/
SET SOURCE_FOLDER=%~dp0sources

